# Generated by Django 2.2.2 on 2019-06-15 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcMstr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Full name')),
                ('address_1', models.CharField(default='-', max_length=50, verbose_name='Address line 1')),
                ('address_2', models.CharField(default='-', max_length=50, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=15, null=True, verbose_name='City')),
                ('pin', models.CharField(default='-', max_length=6, verbose_name='ZIP / Postal code')),
                ('state_code', models.CharField(default='-', max_length=2, verbose_name='State Code')),
                ('gst_no', models.CharField(default='-', max_length=15, verbose_name='GST Number')),
                ('pan_aadhar_no', models.CharField(default='-', max_length=16, verbose_name='PAN / Aadhar Number')),
                ('bp_type', models.CharField(max_length=10, verbose_name='Business Partner Type')),
                ('group_code', models.CharField(blank=True, default='-', max_length=3, verbose_name='Business Group')),
                ('bsgrp', models.IntegerField(default=0, verbose_name='Balance Sheet Group')),
                ('bssubgrp', models.IntegerField(default=0, verbose_name='Balance Sheet Sub-Group')),
                ('opbal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, verbose_name='Opening Balance')),
                ('clbal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, verbose_name='Closing Balance')),
                ('temp_bal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, verbose_name='Temp. Balance')),
                ('user', models.CharField(max_length=20, verbose_name='User')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='Update Date and Time')),
                ('share_dep', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Share-Dep %')),
                ('email', models.CharField(max_length=35, verbose_name='Email')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone')),
                ('pwd', models.CharField(max_length=15, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='ADlocMstr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_code', models.CharField(max_length=8, verbose_name='Location Code')),
                ('loc_name', models.CharField(max_length=15, verbose_name='Location Name')),
            ],
        ),
        migrations.CreateModel(
            name='CompMstr',
            fields=[
                ('company_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Company Code')),
                ('comp_name', models.CharField(max_length=50, verbose_name='Company Name')),
                ('company_type', models.CharField(max_length=9, verbose_name='Company Type')),
                ('address_1', models.CharField(default='-', max_length=50, verbose_name='Address 1')),
                ('address_2', models.CharField(default='-', max_length=50, verbose_name='Address 2')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('pin', models.CharField(default='-', max_length=6, verbose_name='Pincode')),
                ('state_code', models.CharField(max_length=2, verbose_name='State Code')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile')),
                ('gst_no', models.CharField(max_length=15, verbose_name='GST Number')),
                ('pan_no', models.CharField(max_length=10, verbose_name='PAN Number')),
                ('bank_name', models.CharField(max_length=50, verbose_name='Bank Name')),
                ('bank_branch', models.CharField(max_length=50, verbose_name='Bank Branch')),
                ('ac_no', models.CharField(max_length=20, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(max_length=11, verbose_name='IFSC Code')),
                ('jurisdiction', models.CharField(max_length=15, verbose_name='Jurisdiction')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Interest Rate')),
                ('invoice_footer', models.TextField(default='-', max_length=500, verbose_name='Invoice Footer')),
                ('quotation_footer', models.TextField(default='-', max_length=500, verbose_name='Quotation Footer')),
                ('year_start', models.DateField(verbose_name='Financial Year Start')),
                ('year_end', models.DateField(verbose_name='Financial Year End')),
                ('work_start', models.DateField(verbose_name='Work Year Start')),
                ('work_end', models.DateField(verbose_name='Work Year End')),
                ('credit_days', models.IntegerField(verbose_name='Credit Days')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMstr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_code', models.CharField(max_length=8, verbose_name='Item Code')),
                ('it_name', models.CharField(max_length=20, verbose_name='Item Name')),
                ('location', models.CharField(max_length=25, verbose_name='Location')),
                ('sac_code', models.IntegerField(default=998363, verbose_name='SAC Code')),
                ('gst', models.DecimalField(decimal_places=2, default=5, max_digits=2, verbose_name='GST')),
            ],
        ),
        migrations.CreateModel(
            name='ShowMstr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_code', models.CharField(max_length=8, verbose_name='Show Code')),
                ('show_name', models.CharField(max_length=30, verbose_name='Show Name')),
                ('start_date', models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Start Date')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.AcMstr')),
            ],
        ),
        migrations.CreateModel(
            name='SizeMstr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Size')),
            ],
        ),
        migrations.CreateModel(
            name='TypeMstr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=8, verbose_name='Type')),
                ('type_name', models.CharField(max_length=40, verbose_name='Type Name')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vr_no', models.IntegerField(verbose_name='Voucher Number')),
                ('tr_date', models.DateField(verbose_name='Transaction Date')),
                ('remark', models.CharField(max_length=25, verbose_name='Remark')),
                ('start_date', models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Start Date')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount')),
                ('plan_type', models.CharField(max_length=15, verbose_name='Plan Type')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.AcMstr')),
                ('it_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.ItemMstr')),
                ('show_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.ShowMstr')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.SizeMstr')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.TypeMstr')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('pin', models.CharField(max_length=6, verbose_name='Pincode')),
                ('main_company_name', models.CharField(max_length=50, verbose_name='Main Company Name')),
                ('company_code', models.CharField(max_length=8, verbose_name='Company Code')),
                ('module', models.CharField(max_length=1, verbose_name='Module')),
                ('start_date', models.DateField(default='9999-12-31', verbose_name='Start Date')),
                ('end_date', models.DateField(default='9999-12-31', verbose_name='End Date')),
                ('select', models.CharField(default='-', max_length=8, verbose_name='Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='acmstr',
            name='company_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.CompMstr'),
        ),
    ]
