# Generated by Django 2.2.2 on 2019-06-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acmstr',
            name='company_code',
        ),
        migrations.DeleteModel(
            name='ADlocMstr',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='showmstr',
            name='code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='it_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='show_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='size',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.DeleteModel(
            name='AcMstr',
        ),
        migrations.DeleteModel(
            name='CompMstr',
        ),
        migrations.DeleteModel(
            name='ItemMstr',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ShowMstr',
        ),
        migrations.DeleteModel(
            name='SizeMstr',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
