# Generated by Django 2.2.2 on 2019-06-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_auto_20190616_2104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeMstr',
            new_name='TypeMaster',
        ),
    ]
