# Generated by Django 2.2.2 on 2019-06-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_auto_20190616_2151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeMaster',
            new_name='TypeMstr',
        ),
    ]
