# Generated by Django 2.2.2 on 2019-06-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_acmstr_itemmstr_showmstr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showmstr',
            name='code',
        ),
    ]
